repos:

  # Text and YAML Lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: resources/issues.tsv
        args: [--markdown-linebreak-ext=md]

      - id: end-of-file-fixer

      - id: check-yaml

      - id: check-added-large-files
        args: ['--maxkb=10000']

      - id: mixed-line-ending
        args: [--fix=lf]

      - id: detect-private-key

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: [--config=.github/markdown_lint.yaml]

  - repo: local
    hooks:

    # Error if docker compose has a volume mount of an absolute path on the host
    - id: docker-compose-mounts-absolute-path
      name: docker compose mounts absolute path
      entry: bash -c '! git diff-index -p -M --cached HEAD -- docker-compose.yml | grep -qE "^\+\s+-\s*/"'
      language: system
      pass_filenames: true

  # Git Guardian (Secret detection)
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.41.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
