#!/bin/bash

PGPASSWORD=$POSTGRES_PASSWORD PGUSER=$POSTGRES_USER psql postgres \
  -c "select chain_name, run_at, command from timetable.chain left join timetable.task on chain.chain_id = task.task_id;"
