name: Test

# Workflow conditions
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [published]
  workflow_call:

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Credentials
        run: |
          scripts/generate_credentials.sh > .env
        
      - name: Start Container
        run: |
          docker compose up -d

      - name: Healthcheck
        uses: stringbean/docker-healthcheck-action@v3
        with:
          container: postgres
          wait-time: 50
          require-status: running
          require-healthy: true
      
      - name: Get Status
        uses: stringbean/docker-healthcheck-action@v3
        id: postgres-container
        with:
          container: postgres
        
      - name: Display Status
        run: echo "Container is ${{ steps.postgres-container.outputs.status  }}"
          

